(function($){$.fn.dcDrilldown=function(options){var defaults={classWrapper:'dd-wrapper',classMenu:'dd-menu',classParent:'dd-parent',classParentLink:'dd-parent-a',classActive:'active-ul',classHeader:'dd-header',eventType:'click',hoverDelay:300,speed:2000,saveState:false,showCount:false,classCount:'dd-count',classIcon:'dd-icon',linkType:'backlink',resetText:'All',headerTag:'h6',defaultText:'Select Option',includeHdr:true};var options=$.extend(defaults,options);return this.each(function(options){var $dcDrilldownObj=this;$($dcDrilldownObj).addClass(defaults.classMenu);var $wrapper='<div class="'+defaults.classWrapper+'" />';$($dcDrilldownObj).wrap($wrapper);var $dcWrapper=$($dcDrilldownObj).parent();var objIndex=$($dcWrapper).index('.'+defaults.classWrapper);var idHeader=defaults.classHeader+'-'+objIndex;var idWrapper=defaults.classWrapper+'-'+objIndex;$($dcWrapper).attr('id',idWrapper);var $header='<div id="'+idHeader+'" class="'+defaults.classHeader+'"></div>';setUpDrilldown();if(defaults.saveState==true){var cookieId=defaults.classWrapper+'-'+objIndex;checkCookie(cookieId,$dcDrilldownObj);}
resetDrilldown($dcDrilldownObj,$dcWrapper);$('li a',$dcDrilldownObj).click(function(e){$link=this;$activeLi=$(this).parent('li').not('.disabled').stop();$siblingsLi=$($activeLi).siblings();if($('> ul',$activeLi).length){if($($link).hasClass(defaults.classActive)){$('ul a',$activeLi).removeClass(defaults.classActive);resetDrilldown($dcDrilldownObj,$dcWrapper);}else{actionDrillDown($activeLi,$dcWrapper,$dcDrilldownObj);}}
if($(this).next('ul').length>0){e.preventDefault();}});function setUpDrilldown(){$arrow='<span class="'+defaults.classIcon+'"></span>';$($dcDrilldownObj).before($header);var totalWidth=$($dcDrilldownObj).outerWidth();totalWidth+='px';var itemHeight=$('li',$dcDrilldownObj).outerHeight(true);var objUl=$('ul',$dcDrilldownObj);var maxItems=findMaxHeight(objUl);var maxUl=$('[rel="'+maxItems+'"]',objUl);var getIndex=findMaxIndex(maxUl);if(defaults.linkType=='link'){menuHeight=itemHeight*(maxItems+getIndex);}else{menuHeight=itemHeight*maxItems;}
$('li',$dcDrilldownObj).each(function(){$('ul',this).css({marginRight:'-'+totalWidth,marginTop:'0'});if($('> ul',this).length){$(this).addClass(defaults.classParent);$('> a',this).addClass(defaults.classParentLink).append($arrow);if(defaults.showCount==true){var parentLink=$('a:not(.'+defaults.classParentLink+')',this);var countParent=parseInt($(parentLink).length);getCount=countParent;$('> a',this).append(' <span class="'+defaults.classCount+'">('+getCount+')</span>');}}});$('ul',$dcWrapper).each(function(){$('li:last',this).addClass('last');});$('> ul > li:last',$dcWrapper).addClass('last');if(defaults.linkType=='link'){$(objUl).css('top',itemHeight+'px');}
$('ul',$dcWrapper).find('li.active').parents('li').addClass('active');}
$('#'+idHeader).on('click','a',function(e){if($(this).hasClass('link-back')){linkIndex=$('#'+idWrapper+' .'+defaults.classParentLink+'.active-ul').length;linkIndex=linkIndex-2;$('a.'+defaults.classActive+':last',$dcDrilldownObj).removeClass(defaults.classActive);}else{var linkIndex=parseInt($(this).index('#'+idHeader+' a'));if(linkIndex==0){$('a',$dcDrilldownObj).removeClass(defaults.classActive);}else{linkIndex=linkIndex-1;$('a.'+defaults.classActive+':gt('+linkIndex+')',$dcDrilldownObj).removeClass(defaults.classActive);}}
resetDrilldown($dcDrilldownObj,$dcWrapper);e.preventDefault();e.stopPropagation();});});function findMaxHeight(element){var maxValue=undefined;$(element).each(function(){var val=parseInt($('> li',this).length);$(this).attr('rel',val);if(maxValue===undefined||maxValue<val){maxValue=val;}});return maxValue;}
function findMaxIndex(element){var maxIndex=undefined;$(element).each(function(){var val=parseInt($(this).parents('li').length);if(maxIndex===undefined||maxIndex<val){maxIndex=val;}});return maxIndex;}
function actionDrillDown(element,wrapper,obj){var $header=$('.'+defaults.classHeader,wrapper);var getNewBreadcrumb=$(defaults.headerTag,$header).html();var getNewHeaderText=$('> a',element).html();if(defaults.linkType=='breadcrumb'){if(!$('ul',$header).length){$($header).prepend('<ul></ul>');}
if(getNewBreadcrumb==defaults.defaultText){$('ul',$header).append('<li><a href="#" class="first"> '+defaults.resetText+'</a></li>');}else{$('ul',$header).append('<li><a href="#"> '+getNewBreadcrumb+'</a></li>');}}
if(defaults.linkType=='backlink'){if(!$('a',$header).length){$($header).prepend('<a href="#" class="link-back"> '+getNewBreadcrumb+'</a>');}else{$('.link-back',$header).html(getNewBreadcrumb);}}
if(defaults.linkType=='link'){if(!$('a',$header).length){$($header).prepend('<ul><li><a href="#" class="first"> '+defaults.resetText+'</a></li></ul>');}}
updateHeader($header,getNewHeaderText);var activeLink=$('> a',element);$(activeLink).addClass(defaults.classActive);$('> ul li',element).show();$('> ul',element).animate({"margin-right":0},defaults.speed);var $siblingsLi=$(element).siblings();$($siblingsLi).hide();if(defaults.linkType!='link'){$(activeLink).hide();}
if(defaults.saveState==true){var cookieId=$(wrapper).attr('id');createCookie(cookieId,obj);}}
function actionDrillUp(element,obj,wrapper){var $header=$('.'+defaults.classHeader,wrapper);var activeLink=$('> a',element);var checklength=$('.'+defaults.classActive,wrapper).length;var activeIndex=$(activeLink).index('.'+defaults.classActive,wrapper);var totalWidth=$(obj).outerWidth(true);$('ul',element).css('margin-right',-totalWidth+'px');$(activeLink).addClass(defaults.classActive);$('> ul li',element).show();$('a',element).show();var getNewHeaderText=$('> a',element).html();$(defaults.headerTag,$header).html(getNewHeaderText);if(defaults.linkType=='breadcrumb'){var breadcrumbIndex=activeIndex-1;$('a:gt('+activeIndex+')',$header).remove();}}
function updateHeader(obj,html){if(defaults.includeHdr==true){if($(defaults.headerTag,obj).length){$(defaults.headerTag,obj).html(html);}else{$(obj).append('<'+defaults.headerTag+'>'+html+'</'+defaults.headerTag+'>');}}}
function resetDrilldown(obj,wrapper){var $header=$('.'+defaults.classHeader,wrapper);$('ul',$header).remove();$('a',$header).remove();$('li',obj).show();$('a',obj).show();var totalWidth=$(obj).outerWidth(true);if(defaults.linkType=="link"){if($('a.'+defaults.classActive+':last',obj).parent('li').length){var lastActive=$('a.'+defaults.classActive+':last',obj).parent('li');$('ul',lastActive).css('margin-right',-totalWidth+'px');}else{$('ul',obj).css('margin-right',-totalWidth+'px');}}else{$('ul',obj).css('margin-right',-totalWidth+'px');}
updateHeader($header,defaults.defaultText);if(defaults.saveState==true){var cookieId=$(wrapper).attr('id');createCookie(cookieId,obj);}
$('a.'+defaults.classActive,obj).each(function(i){var $activeLi=$(this).parent('li').stop();actionDrillDown($activeLi,wrapper,obj);});}
function checkCookie(cookieId,obj){var cookieVal=$.cookie(cookieId);if(cookieVal!=null){var activeArray=cookieVal.split(',');$.each(activeArray,function(index,value){value=parseInt(value)+0;var $cookieLi=$('li:eq('+value+')',obj);$('> a',$cookieLi).addClass(defaults.classActive);});}}
function createCookie(cookieId,obj){var activeIndex=[];$('a.'+defaults.classActive,obj).each(function(i){var $arrayItem=$(this).parent('li');var itemIndex=$('li',obj).index($arrayItem);activeIndex.push(itemIndex);});$.cookie(cookieId,activeIndex,{path:'/'});}};})(jQuery);(function(factory){if(typeof define==='function'&&define.amd){define(['jquery'],factory);}else if(typeof exports==='object'){factory(require('jquery'));}else{factory(jQuery);}}(function($){var pluses=/\+/g;function encode(s){return config.raw?s:encodeURIComponent(s);}
function decode(s){return config.raw?s:decodeURIComponent(s);}
function stringifyCookieValue(value){return encode(config.json?JSON.stringify(value):String(value));}
function parseCookieValue(s){if(s.indexOf('"')===0){s=s.slice(1,-1).replace(/\\"/g,'"').replace(/\\\\/g,'\\');}
try{s=decodeURIComponent(s.replace(pluses,' '));return config.json?JSON.parse(s):s;}catch(e){}}
function read(s,converter){var value=config.raw?s:parseCookieValue(s);return $.isFunction(converter)?converter(value):value;}
var config=$.cookie=function(key,value,options){if(arguments.length>1&&!$.isFunction(value)){options=$.extend({},config.defaults,options);if(typeof options.expires==='number'){var days=options.expires,t=options.expires=new Date();t.setTime(+t+days*864e+5);}
return(document.cookie=[encode(key),'=',stringifyCookieValue(value),options.expires?'; expires='+options.expires.toUTCString():'',options.path?'; path='+options.path:'',options.domain?'; domain='+options.domain:'',options.secure?'; secure':''].join(''));}
var result=key?undefined:{};var cookies=document.cookie?document.cookie.split('; '):[];for(var i=0,l=cookies.length;i<l;i++){var parts=cookies[i].split('=');var name=decode(parts.shift());var cookie=parts.join('=');if(key&&key===name){result=read(cookie,value);break;}
if(!key&&(cookie=read(cookie))!==undefined){result[name]=cookie;}}
return result;};config.defaults={};$.removeCookie=function(key,options){if($.cookie(key)===undefined){return false;}
$.cookie(key,'',$.extend({},options,{expires:-1}));return!$.cookie(key);};}));